### ISSUE TITLE
Too many fish spawn in lush forest

### ISSUE THREAD

**Issue by SaxophOnyx** [Albertsmods/Lush-Forest#2]
![2022-01-22_23 49 05](https://user-images.githubusercontent.com/86550156/150655091-24743ef5-a607-460e-b4b4-d5c7231a0a90.png)
An excessive amount of fish starts spawn after maybe a minute near the water in lush forest. Everything seems to be normal in usual oceans.

**Comment by Albertsmods** [comment]
Thanks for reporting, it will be fixed in the next update

**Comment by Albertsmods** [comment]
https://www.curseforge.com/minecraft/mc-mods/lush-forests 
fixed in latest update for both versions
