### ISSUE TITLE
Tropical fish cause heavy lag

### ISSUE THREAD

**Issue by Hunter24681** [Albertsmods/Lush-Forest#5]
I'm playing a modpack that includes this mod, and when I get near one of the lush forests on my map I get the following errors in console and a drop to 1-5fps

```
[23:56:45] [Server thread/ERROR]: Unknown structure piece id: valley:tide_pool
[23:56:46] [Worker-Main-5/ERROR]: Signature is missing from textures payload
[23:56:50] [Server thread/ERROR]: Unknown structure piece id: valley:tide_pool
[23:56:50] [Server thread/ERROR]: Unknown structure piece id: valley:research_station
```

As this mod doesn't appear to have a config file I cannot tell for certain that these structures are from this mod, so if not I apologize.  From the valley:tide_pool one it seems like it at least.  Else these 2 structures don't seem to have proper ids

**Comment by Hunter24681** [comment]
On some more searching it was actually the massive amounts of tropical fish that spawn around in the biome, the error above is unrelated to the lag.  A /kill showed 9.5k entities killed, all the fish died, and the lag disappeared.  Not sure if this is still something within the scope of the mod

**Comment by Albertsmods** [comment]
Those structures aren't from my mod, what version of the mod are you playing? In the latest version, the fish lag has been fixed.

**Comment by Hunter24681** [comment]
I'm on 1.1.0 fabric as part of a modpack so can't update unfortunately.  I'll let the modpack authors know.  It looks like the fix beyond 1.1.0 isn't released yet?

**Comment by Albertsmods** [comment]
1.2.0 has been released. https://www.curseforge.com/minecraft/mc-mods/lush-forests/files/3633498

**Comment by Hunter24681** [comment]
Oh great, thank you!
