### ISSUE TITLE
Fabric Biome API Crash?

### ISSUE THREAD

**Issue by Niketats** [Albertsmods/Lush-Forest#7]
[crash-2022-03-29_01.16.18-server.txt](https://github.com/Albertsmods/Lush-Forest/files/8366712/crash-2022-03-29_01.16.18-server.txt)

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/jykLt2xNAU

**Comment by TheButterbrotMan** [comment]
For ways to solve see: https://github.com/ExDrill/CaveEnhancementsMod/issues/1#event-6322618199

**Comment by ExDrill** [comment]
The reason it was crashing wasn't because of biome registeration, but it's something to do with the order of feature placement in the biome itself.

**Comment by Albertsmods** [comment]
> For ways to solve see: [ExDrill/CaveEnhancementsMod#1 (comment)](https://github.com/ExDrill/CaveEnhancementsMod/issues/1#event-6322618199)

Thanks, fixing it now.

**Comment by Albertsmods** [comment]
Fixed in v1.3.1
